#ifndef __ASM_ARCH_REGS_CORE_H
#define __ASM_ARCH_REGS_CORE_H

#define	V7_PRIVATE_CPUCORE				AP_GIC_BASE
#define	ICDDCR_BASEADDR					(V7_PRIVATE_CPUCORE + 0x1000)
#define	ICCICR_BASEADDR					(V7_PRIVATE_CPUCORE + 0x2000)
#define	PRITIMERWDT_BASEADDR				(V7_PRIVATE_CPUCORE + 0x600)

#define	ICDDCR						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x00 ))			
#define	ICDICTR						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x04 ))
#define	ICDIIDR						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x08 ))

#define	ICDISR						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x80 ))
#define	ICDISR0						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x80 ))
#define	ICDISR1						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x84 ))
#define	ICDISR2						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x88 ))

#define	ICDISER						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x100 ))
#define	ICDISER0					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x100 ))
#define	ICDISER1					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x104 ))
#define	ICDISER2					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x108 ))

#define	ICDICER						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x180 ))
#define	ICDICER0					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x180 ))
#define	ICDICER1					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x184 ))
#define	ICDICER2					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x188 ))

#define	ICDISPR						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x200 ))
#define	ICDISPR0					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x200 ))
#define	ICDISPR1					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x204 ))
#define	ICDISPR2					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x208 ))

#define	ICDICPR						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x280 ))
#define	ICDICPR0					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x280 ))
#define	ICDICPR1					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x284 ))
#define	ICDICPR2					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x288 ))

#define	ICDABR						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x300 ))
#define	ICDABR0						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x300 ))
#define	ICDABR1						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x304 ))
#define	ICDABR2						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x308 ))

#define	ICDIPR						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x400 ))
#define	ICDIPR0						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x400 ))
#define	ICDIPR1						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x404 ))
#define	ICDIPR2						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x408 ))
#define	ICDIPR3						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x40C ))
#define	ICDIPR4						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x410 ))
#define	ICDIPR5						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x414 ))
#define	ICDIPR6						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x418 ))
#define	ICDIPR7						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x41C ))
#define	ICDIPR8						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x420 ))
#define	ICDIPR9						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x424 ))
#define	ICDIPR10					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x428 ))
#define	ICDIPR11					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x42C ))
#define	ICDIPR12					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x430 ))
#define	ICDIPR13					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x434 ))
#define	ICDIPR14					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x438 ))
#define	ICDIPR15					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x43C ))
#define	ICDIPR16					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x440 ))
#define	ICDIPR17					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x444 ))
#define	ICDIPR18					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x448 ))
#define	ICDIPR19					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x44C ))
#define	ICDIPR20					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x450 ))
#define	ICDIPR21					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x454 ))
#define	ICDIPR22					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x458 ))

#define	ICDIPTR						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x800 ))
#define	ICDIPTR0					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x800 ))
#define	ICDIPTR1					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x804 ))
#define	ICDIPTR2					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x808 ))
#define	ICDIPTR3					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x80c ))
#define	ICDIPTR4					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x810 ))
#define	ICDIPTR5					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x814 ))
#define	ICDIPTR6					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x818 ))
#define	ICDIPTR7					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x81c ))
#define	ICDIPTR8					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x820 ))
#define	ICDIPTR9					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x824 ))
#define	ICDIPTR10					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x828 ))
#define	ICDIPTR11					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x82c ))
#define	ICDIPTR12					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x830 ))
#define	ICDIPTR13					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x834 ))
#define	ICDIPTR14					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x838 ))
#define	ICDIPTR15					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x83c ))
#define	ICDIPTR16					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x840 ))
#define	ICDIPTR17					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x844 ))
#define	ICDIPTR18					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x848 ))
#define	ICDIPTR19					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x84c ))
#define	ICDIPTR20					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x850 ))
#define	ICDIPTR21					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x854 ))
#define	ICDIPTR22					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0x858 ))

#define	ICDICFR						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0xc00 ))
#define	ICDICFR0					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0xc00 ))
#define	ICDICFR1					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0xc04 ))
#define	ICDICFR2					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0xc08 ))
#define	ICDICFR3					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0xc0c ))
#define	ICDICFR4					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0xc10 ))
#define	ICDICFR5					((volatile unsigned  int*)( ICDDCR_BASEADDR + 0xc14 ))

#define	ICDSGIR						((volatile unsigned  int*)( ICDDCR_BASEADDR + 0xf00 ))

#define	ICCICR						((volatile unsigned  int*)( ICCICR_BASEADDR + 0x00 ))			
#define	ICCPMR						((volatile unsigned  int*)( ICCICR_BASEADDR + 0x04 ))
#define	ICCBPR						((volatile unsigned  int*)( ICCICR_BASEADDR + 0x08 ))
#define	ICCIAR						((volatile unsigned  int*)( ICCICR_BASEADDR + 0x0c ))
#define	ICCEOIR						((volatile unsigned  int*)( ICCICR_BASEADDR + 0x10 ))
#define	ICCRPR						((volatile unsigned  int*)( ICCICR_BASEADDR + 0x14 ))
#define	ICCHPIR						((volatile unsigned  int*)( ICCICR_BASEADDR + 0x18 ))
#define	ICCABPR						((volatile unsigned  int*)( ICCICR_BASEADDR + 0x1c ))
#define	ICCIIDR						((volatile unsigned  int*)( ICCICR_BASEADDR + 0xfc ))

#define PRITIMERLOAD					((volatile unsigned  int*)( PRITIMERWDT_BASEADDR + 0x00 ))			
#define PRITIMERCNT					((volatile unsigned  int*)( PRITIMERWDT_BASEADDR + 0x04 ))
#define PRITIMERCTL					((volatile unsigned  int*)( PRITIMERWDT_BASEADDR + 0x08 ))
#define PRITIMERINTSTATUS				((volatile unsigned  int*)( PRITIMERWDT_BASEADDR + 0x0c ))
#define PRIWDTLOAD					((volatile unsigned  int*)( PRITIMERWDT_BASEADDR + 0x20 ))
#define PRIWDTCNT					((volatile unsigned  int*)( PRITIMERWDT_BASEADDR + 0x24 ))
#define PRIWDTCTL					((volatile unsigned  int*)( PRITIMERWDT_BASEADDR + 0x28 ))
#define PRIWDTINTSTATUS					((volatile unsigned  int*)( PRITIMERWDT_BASEADDR + 0x2c ))
#define PRIWDTRSTSTATUS					((volatile unsigned  int*)( PRITIMERWDT_BASEADDR + 0x30 ))
#define PRIWDTDISABLE					((volatile unsigned  int*)( PRITIMERWDT_BASEADDR + 0x34 ))

#endif /*__ASM_ARCH_REGS_CORE_H*/
