#ifndef __ASM_ARCH_REGS_SECURITY_H
#define __ASM_ARCH_REGS_SECURITY_H

#define SECURITY_CTRL	 			(AP_SECURITY_BASE + 0x00)
#define SECURITY_AP_PWR_CTRL 			(AP_SECURITY_BASE + 0x04)
#define	SECURITY_FSM_MODE			(AP_SECURITY_BASE + 0x10)
#define SECURITY_KEY_CTRL			(AP_SECURITY_BASE + 0x14)
#define	SECURITY_CONVS0_NUM			(AP_SECURITY_BASE + 0x18)
#define	SECURITY_CONVS1_NUM			(AP_SECURITY_BASE + 0x1c)
#define	SECURITY_INTR_EN			(AP_SECURITY_BASE + 0x20)
#define	SECURITY_INTR_STATUS			(AP_SECURITY_BASE + 0x24)
#define	SECURITY_INTR_RAW			(AP_SECURITY_BASE + 0x28)
#define	SECURITY_LP_EN				(AP_SECURITY_BASE + 0x30)
#define	SECURITY_DEBUG_CTRL0			(AP_SECURITY_BASE + 0x34)
#define	SECURITY_DEBUG_CTRL1			(AP_SECURITY_BASE + 0x38)
#define	SECURITY_SMMU_CTRL			(AP_SECURITY_BASE + 0x3c)
#define	EFUSE_CTRL				(AP_SECURITY_BASE + 0x200)
#define	EFUSE_MODE				(AP_SECURITY_BASE + 0x204)
#define	EFUSE_ADDR				(AP_SECURITY_BASE + 0x208)
#define	EFUSE_LENGTH				(AP_SECURITY_BASE + 0x20c)
#define	EFUSE_CNT				(AP_SECURITY_BASE + 0x210)
#define	EFUSE_DATA_BASE				(AP_SECURITY_BASE + 0x220)
#define	EFUSE_DATA_BASE_END			(AP_SECURITY_BASE + 0x31c)
#define	EFUSE_PGM_DATA_BASE			(AP_SECURITY_BASE + 0x320)
#define	EFUSE_PGM_DATA_BASE_END			(AP_SECURITY_BASE + 0x39c)

/* SECURITY_INTR */
#define SECURITY_INTR_KEY1_POP			10
#define SECURITY_INTR_KEY0_POP			9
#define SECURITY_INTR_KEY1_PUSH			8
#define SECURITY_INTR_KEY0_PUSH			7
#define SECURITY_INTR_CONVS12NONSEC		6
#define SECURITY_INTR_SEC2CONVS1		5
#define SECURITY_INTR_CONVS02SEC		4
#define SECURITY_INTR_NONSEC2CONVS0		3
#define SECURITY_INTR_ADDR			2
#define SECURITY_INTR_PGM			1
#define SECURITY_INTR_EFUSE			0

/* EFUSE_CTRL */
#define EFUSE_CTRL_ENABLE			0

/* EFUSE_MODE */
#define EFUSE_MODE_MODE				0

/* EFUSE Address & length */
#define EFUSE_ADDR_CHIP_ID			(0x0)
#define EFUSE_LENGTH_CHIP_ID			(0x20)

#endif
